 Network lpicanco_default  Creating
 Network lpicanco_default  Created
 Container lpicanco-db-1  Creating
 Container lpicanco-db-1  Created
 Container lpicanco-api02-1  Creating
 Container lpicanco-api01-1  Creating
 Container lpicanco-api01-1  Created
 Container lpicanco-api02-1  Created
 Container lpicanco-nginx-1  Creating
 Container lpicanco-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-02-11 00:58:37.001 UTC [47] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-11 00:58:37.004 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-11 00:58:37.013 UTC [50] LOG:  database system was shut down at 2024-02-11 00:58:36 UTC
db-1     | 2024-02-11 00:58:37.034 UTC [47] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
db-1     | You are now connected to database "dogfight" as user "dogfight_user".
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | DO
db-1     | 
db-1     | 
db-1     | 2024-02-11 00:58:37.338 UTC [47] LOG:  received fast shutdown request
db-1     | waiting for server to shut down....2024-02-11 00:58:37.340 UTC [47] LOG:  aborting any active transactions
db-1     | 2024-02-11 00:58:37.343 UTC [47] LOG:  background worker "logical replication launcher" (PID 53) exited with exit code 1
db-1     | 2024-02-11 00:58:37.345 UTC [48] LOG:  shutting down
db-1     | 2024-02-11 00:58:37.347 UTC [48] LOG:  checkpoint starting: shutdown immediate
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | 2024-02-11 00:58:37.644 UTC [48] LOG:  checkpoint complete: wrote 937 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.242 s, sync=0.045 s, total=0.299 s; sync files=306, longest=0.016 s, average=0.001 s; distance=4287 kB, estimate=4287 kB; lsn=0/191A5F8, redo lsn=0/191A5F8
db-1     | 2024-02-11 00:58:37.653 UTC [47] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-11 00:58:37.788 UTC [1] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-11 00:58:37.789 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-11 00:58:37.789 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-11 00:58:37.811 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-11 00:58:37.821 UTC [66] LOG:  database system was shut down at 2024-02-11 00:58:37 UTC
db-1     | 2024-02-11 00:58:37.835 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/02/11 00:58:38 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:9999/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/11 00:58:38 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:9999/clientes/1/extrato", host: "localhost:9999"
api02-1  | ðŸ¦€Server running at http://localhost:9999/
api01-1  | ðŸ¦€Server running at http://localhost:9999/
nginx-1  | 2024/02/11 00:58:40 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/11 00:58:42 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/11 00:58:44 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/11 00:58:46 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/11 00:58:48 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
api01-1 exited with code 0
api02-1 exited with code 0
api02-1 exited with code 0
api01-1 exited with code 0
db-1     | 2024-02-11 01:03:06.950 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-11 01:03:06.957 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-11 01:03:06.960 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-11 01:03:06.960 UTC [64] LOG:  shutting down
db-1     | 2024-02-11 01:03:06.962 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-11 01:03:07.081 UTC [64] LOG:  checkpoint complete: wrote 618 buffers (3.8%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.069 s, sync=0.031 s, total=0.122 s; sync files=32, longest=0.021 s, average=0.001 s; distance=15496 kB, estimate=15496 kB; lsn=0/283C718, redo lsn=0/283C718
db-1     | 2024-02-11 01:03:07.092 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
