 Network rinha-gateway-2024q1  Creating
 Network rinha-gateway-2024q1  Created
 Container marcusdacoregio-db-1  Creating
 Container marcusdacoregio-db-1  Created
 Container marcusdacoregio-api02-1  Creating
 Container marcusdacoregio-api01-1  Creating
 Container marcusdacoregio-api01-1  Created
 Container marcusdacoregio-api02-1  Created
 Container marcusdacoregio-nginx-1  Creating
 Container marcusdacoregio-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
api01-1  | 
api01-1  |   .   ____          _            __ _ _
api01-1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
api01-1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
api01-1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
api01-1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
api01-1  |  =========|_|==============|___/=/_/_/_/
api01-1  |  :: Spring Boot ::                (v3.2.2)
api01-1  | 
api01-1  | 2024-02-18T18:20:32.664Z  INFO 1 --- [           main] c.m.rinhaapi.RinhaApiApplication         : Starting AOT-processed RinhaApiApplication using Java 21.0.2 with PID 1 (/workspace/com.marcusdacoregio.rinhaapi.RinhaApiApplication started by cnb in /workspace)
api01-1  | 2024-02-18T18:20:32.665Z  INFO 1 --- [           main] c.m.rinhaapi.RinhaApiApplication         : No active profile set, falling back to 1 default profile: "default"
api02-1  | 
api02-1  |   .   ____          _            __ _ _
api02-1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
api02-1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
api02-1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
api02-1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
api02-1  |  =========|_|==============|___/=/_/_/_/
api02-1  |  :: Spring Boot ::                (v3.2.2)
api02-1  | 
api02-1  | 2024-02-18T18:20:32.668Z  INFO 1 --- [           main] c.m.rinhaapi.RinhaApiApplication         : Starting AOT-processed RinhaApiApplication using Java 21.0.2 with PID 1 (/workspace/com.marcusdacoregio.rinhaapi.RinhaApiApplication started by cnb in /workspace)
api02-1  | 2024-02-18T18:20:32.668Z  INFO 1 --- [           main] c.m.rinhaapi.RinhaApiApplication         : No active profile set, falling back to 1 default profile: "default"
api01-1  | 2024-02-18T18:20:32.716Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
api01-1  | 2024-02-18T18:20:32.717Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
api01-1  | 2024-02-18T18:20:32.717Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
api02-1  | 2024-02-18T18:20:32.722Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8081 (http)
api02-1  | 2024-02-18T18:20:32.723Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
api02-1  | 2024-02-18T18:20:32.723Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
api01-1  | 2024-02-18T18:20:32.728Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
api01-1  | 2024-02-18T18:20:32.728Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 63 ms
api02-1  | 2024-02-18T18:20:32.733Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
api02-1  | 2024-02-18T18:20:32.733Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 65 ms
api01-1  | 2024-02-18T18:20:32.747Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
api02-1  | 2024-02-18T18:20:32.751Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
db-1     | performing post-bootstrap initialization ... ok
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | waiting for server to start....2024-02-18 18:20:33.908 UTC [48] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-18 18:20:33.911 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-18 18:20:33.924 UTC [51] LOG:  database system was shut down at 2024-02-18 18:20:33 UTC
db-1     | 2024-02-18 18:20:33.931 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db-1     | 
db-1     | waiting for server to shut down...2024-02-18 18:20:34.116 UTC [48] LOG:  received fast shutdown request
db-1     | .2024-02-18 18:20:34.120 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-02-18 18:20:34.122 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-18 18:20:34.123 UTC [49] LOG:  shutting down
db-1     | 2024-02-18 18:20:34.126 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-18 18:20:34.613 UTC [49] LOG:  checkpoint complete: wrote 923 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.380 s, sync=0.096 s, total=0.491 s; sync files=301, longest=0.071 s, average=0.001 s; distance=4257 kB, estimate=4257 kB; lsn=0/1913068, redo lsn=0/1913068
db-1     | 2024-02-18 18:20:34.618 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-18 18:20:34.740 UTC [1] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-18 18:20:34.740 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-18 18:20:34.740 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-18 18:20:34.751 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-18 18:20:34.762 UTC [64] LOG:  database system was shut down at 2024-02-18 18:20:34 UTC
db-1     | 2024-02-18 18:20:34.763 UTC [65] FATAL:  the database system is starting up
db-1     | 2024-02-18 18:20:34.763 UTC [66] FATAL:  the database system is starting up
db-1     | 2024-02-18 18:20:34.768 UTC [1] LOG:  database system is ready to accept connections
api02-1  | 2024-02-18T18:20:35.782Z  INFO 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@2c6d5a1e
api02-1  | 2024-02-18T18:20:35.782Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
api01-1  | 2024-02-18T18:20:35.782Z  INFO 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@6508c28
api01-1  | 2024-02-18T18:20:35.782Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
api01-1  | 2024-02-18T18:20:35.784Z  INFO 1 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 9.22.3 by Redgate
api01-1  | 2024-02-18T18:20:35.784Z  INFO 1 --- [           main] o.f.c.internal.license.VersionPrinter    : See release notes here: https://rd.gt/416ObMi
api01-1  | 2024-02-18T18:20:35.784Z  INFO 1 --- [           main] o.f.c.internal.license.VersionPrinter    : 
api01-1  | 2024-02-18T18:20:35.784Z  WARN 1 --- [           main] o.f.c.i.s.classpath.ClassPathScanner     : Unable to scan location: /db/migration (unsupported protocol: resource)
api02-1  | 2024-02-18T18:20:35.784Z  INFO 1 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 9.22.3 by Redgate
api02-1  | 2024-02-18T18:20:35.784Z  INFO 1 --- [           main] o.f.c.internal.license.VersionPrinter    : See release notes here: https://rd.gt/416ObMi
api02-1  | 2024-02-18T18:20:35.784Z  INFO 1 --- [           main] o.f.c.internal.license.VersionPrinter    : 
api02-1  | 2024-02-18T18:20:35.784Z  WARN 1 --- [           main] o.f.c.i.s.classpath.ClassPathScanner     : Unable to scan location: /db/migration (unsupported protocol: resource)
api01-1  | 2024-02-18T18:20:35.784Z  WARN 1 --- [           main] o.f.c.i.s.classpath.ClassPathScanner     : Unable to scan location: /db/migration (unsupported protocol: resource)
api02-1  | 2024-02-18T18:20:35.784Z  WARN 1 --- [           main] o.f.c.i.s.classpath.ClassPathScanner     : Unable to scan location: /db/migration (unsupported protocol: resource)
api02-1  | 2024-02-18T18:20:35.785Z  INFO 1 --- [           main] org.flywaydb.core.FlywayExecutor         : Database: jdbc:postgresql://db:5432/rinha (PostgreSQL 16.1)
api01-1  | 2024-02-18T18:20:35.785Z  INFO 1 --- [           main] org.flywaydb.core.FlywayExecutor         : Database: jdbc:postgresql://db:5432/rinha (PostgreSQL 16.1)
api01-1  | 2024-02-18T18:20:35.786Z  WARN 1 --- [           main] o.f.c.internal.database.base.Database    : Flyway upgrade recommended: PostgreSQL 16.1 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 15.
api02-1  | 2024-02-18T18:20:35.786Z  WARN 1 --- [           main] o.f.c.internal.database.base.Database    : Flyway upgrade recommended: PostgreSQL 16.1 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 15.
api01-1  | 2024-02-18T18:20:35.788Z  INFO 1 --- [           main] o.f.c.i.s.JdbcTableSchemaHistory         : Schema history table "public"."flyway_schema_history" does not exist yet
api02-1  | 2024-02-18T18:20:35.788Z  INFO 1 --- [           main] o.f.c.i.s.JdbcTableSchemaHistory         : Schema history table "public"."flyway_schema_history" does not exist yet
api02-1  | 2024-02-18T18:20:35.789Z  INFO 1 --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 2 migrations (execution time 00:00.001s)
api01-1  | 2024-02-18T18:20:35.789Z  INFO 1 --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 2 migrations (execution time 00:00.001s)
api02-1  | 2024-02-18T18:20:35.793Z  INFO 1 --- [           main] o.f.c.i.s.JdbcTableSchemaHistory         : Creating Schema History table "public"."flyway_schema_history" ...
api02-1  | 2024-02-18T18:20:35.818Z  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "public": << Empty Schema >>
api02-1  | 2024-02-18T18:20:35.819Z  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "public" to version "1.0.0 - cria tabelas"
api02-1  | 2024-02-18T18:20:35.839Z  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "public" to version "1.0.1 - clientes iniciais"
api02-1  | 2024-02-18T18:20:35.843Z  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Successfully applied 2 migrations to schema "public", now at version v1.0.1 (execution time 00:00.014s)
api02-1  | 2024-02-18T18:20:35.939Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8081 (http) with context path ''
api02-1  | 2024-02-18T18:20:35.939Z  INFO 1 --- [           main] c.m.rinhaapi.RinhaApiApplication         : Started RinhaApiApplication in 3.302 seconds (process running for 3.307)
api01-1  | 2024-02-18T18:20:36.795Z  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "public": 1.0.1
api01-1  | 2024-02-18T18:20:36.795Z  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Schema "public" is up to date. No migration necessary.
api01-1  | 2024-02-18T18:20:36.845Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path ''
api01-1  | 2024-02-18T18:20:36.846Z  INFO 1 --- [           main] c.m.rinhaapi.RinhaApiApplication         : Started RinhaApiApplication in 4.212 seconds (process running for 4.218)
api01-1  | 2024-02-18T18:20:36.846Z  INFO 1 --- [omcat-handler-0] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
api01-1  | 2024-02-18T18:20:36.846Z  INFO 1 --- [omcat-handler-0] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
api01-1  | 2024-02-18T18:20:36.847Z  INFO 1 --- [omcat-handler-0] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
db-1     | 2024-02-18 18:20:42.141 UTC [107] FATAL:  role "root" does not exist
api02-1  | 2024-02-18T18:20:42.175Z  INFO 1 --- [omcat-handler-0] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
api02-1  | 2024-02-18T18:20:42.175Z  INFO 1 --- [omcat-handler-0] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
api02-1  | 2024-02-18T18:20:42.175Z  INFO 1 --- [omcat-handler-0] o.s.web.servlet.DispatcherServlet        : Completed initialization in 0 ms
api01-1  | 2024-02-18T18:20:46.182Z  WARN 1 --- [mcat-handler-42] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/4/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api02-1  | 2024-02-18T18:20:46.183Z  WARN 1 --- [mcat-handler-41] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/5/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api02-1  | 2024-02-18T18:20:46.184Z  WARN 1 --- [mcat-handler-42] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/2/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api01-1  | 2024-02-18T18:20:46.185Z  WARN 1 --- [mcat-handler-45] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/4/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api02-1  | 2024-02-18T18:20:46.185Z  WARN 1 --- [mcat-handler-43] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/3/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api01-1  | 2024-02-18T18:20:46.187Z  WARN 1 --- [mcat-handler-46] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/2/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api02-1  | 2024-02-18T18:20:46.186Z  WARN 1 --- [mcat-handler-44] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/1/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api02-1  | 2024-02-18T18:20:46.188Z  WARN 1 --- [mcat-handler-45] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/1/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api01-1  | 2024-02-18T18:20:46.188Z  WARN 1 --- [mcat-handler-47] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/4/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api01-1  | 2024-02-18T18:20:46.189Z  WARN 1 --- [mcat-handler-48] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/5/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api02-1  | 2024-02-18T18:20:46.188Z  WARN 1 --- [mcat-handler-46] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/3/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api01-1  | 2024-02-18T18:20:46.189Z  WARN 1 --- [mcat-handler-49] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/2/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api02-1  | 2024-02-18T18:20:46.191Z  WARN 1 --- [mcat-handler-47] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/3/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api02-1  | 2024-02-18T18:20:46.191Z  WARN 1 --- [mcat-handler-48] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/1/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api01-1  | 2024-02-18T18:20:46.192Z  WARN 1 --- [mcat-handler-50] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/5/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
db-1     | 2024-02-18 18:20:52.224 UTC [115] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:21:02.295 UTC [123] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:21:12.379 UTC [132] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:21:22.464 UTC [140] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:21:32.532 UTC [149] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:21:42.608 UTC [157] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:21:52.680 UTC [166] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:22:02.755 UTC [174] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:22:12.829 UTC [183] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:22:22.909 UTC [191] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:22:32.986 UTC [200] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:22:43.066 UTC [208] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:22:53.194 UTC [217] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:23:03.278 UTC [225] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:23:13.362 UTC [234] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:23:23.449 UTC [242] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:23:33.528 UTC [251] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:23:43.613 UTC [258] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:23:53.692 UTC [267] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:24:03.772 UTC [276] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:24:13.853 UTC [285] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:24:23.932 UTC [293] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:24:34.018 UTC [302] FATAL:  role "root" does not exist
db-1     | 2024-02-18 18:24:44.106 UTC [310] FATAL:  role "root" does not exist
nginx-1 exited with code 0
nginx-1 exited with code 0
api02-1  | 2024-02-18T18:24:50.345Z  INFO 1 --- [ionShutdownHook] o.s.b.w.e.tomcat.GracefulShutdown        : Commencing graceful shutdown. Waiting for active requests to complete
api02-1  | 2024-02-18T18:24:50.345Z  INFO 1 --- [tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown        : Graceful shutdown complete
api02-1  | 2024-02-18T18:24:50.346Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
api01-1  | 2024-02-18T18:24:50.347Z  INFO 1 --- [ionShutdownHook] o.s.b.w.e.tomcat.GracefulShutdown        : Commencing graceful shutdown. Waiting for active requests to complete
api01-1  | 2024-02-18T18:24:50.363Z  INFO 1 --- [tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown        : Graceful shutdown complete
api02-1  | 2024-02-18T18:24:50.353Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
api01-1  | 2024-02-18T18:24:50.365Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
api01-1  | 2024-02-18T18:24:50.374Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
api02-1 exited with code 0
api02-1 exited with code 143
api01-1 exited with code 0
api01-1 exited with code 143
db-1     | 2024-02-18 18:24:51.363 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-18 18:24:51.367 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-18 18:24:51.369 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-18 18:24:51.369 UTC [62] LOG:  shutting down
db-1     | 2024-02-18 18:24:51.372 UTC [62] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-18 18:24:51.612 UTC [62] LOG:  checkpoint complete: wrote 800 buffers (4.9%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.014 s, sync=0.199 s, total=0.243 s; sync files=80, longest=0.190 s, average=0.003 s; distance=4170 kB, estimate=4170 kB; lsn=0/1D259D0, redo lsn=0/1D259D0
db-1     | 2024-02-18 18:24:51.616 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
